{% set name = "spyder-memory-profiler" %}
{% set version = "0.2.1" %}
{% set hash = "49ee86d74dd05797788b722113db501912303739ac707aecdc585885ccd3c237" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip

  run:
    - memory_profiler
    - python
    - spyder >=4,<5

test:
  # On Linux, importing requires an X server
  files:
    - test_import.py  # [linux]
  imports:
    - spyder_memory_profiler  # [not linux]

about:
  home: https://github.com/spyder-ide/spyder-memory-profiler
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Spyder plugin that integrates the Python memory profiler.
  description: |
    This is a plugin for the Spyder IDE that integrates the Python memory profiler.
    It allows you to see the memory usage in every line.
  dev_url: https://github.com/spyder-ide/spyder-memory-profiler

extra:
  recipe-maintainers:
    - ccordoba12
    - jitseniesen
    - goanpeca
