travis:
  secure:
    BINSTAR_TOKEN: sUIljje62gyUkWEZ3MCCLZSDHPtNeqXoLZ0j5V5eNrKiVKmIOemDAzCoNnfeOjOrzNo5FvrS99HXh1WKxMltxDXALgiRB35AKsMj/vjzqc8pQECVw+kHmAwR14eUyina+EC9Pv/mA0p8P7oVyqdOYgAY3CSlDeP4qLDcbs0gBtzmzDU4piomvaoxSekInYNLAsGnpGpjlQdZfeP7cICG2tKZg9PyeNhYCwYxPiHvSptslO8R6DQY5jKX3INd+WWhXgPI3SuvOEPwlSFPU1YvZSuyTCJTEV8ai0+cikYzSkArzvGLTSnONe/zcG49e3yCwkze/+z76gMCZcQBVergFuxE+RbfpJxEM54RUqbySgA/FFyHRu/aZMy0K+B/JsM7TjrnUYAYeXlU6jUdwS/A5i+ypnvyjIIfc2fDmZMBQieHERi5n45aVRYbPEkUs+6qvVicemLJz2Ar2WoCMAzEFtVhsLHxj2F80JGmu6mHZ9X6QcqdPvYXBunyBt0Da3RhMdHwpovEOg/Oa1Q1zts98kFzBopPzwjjU2057SHiKo7nNpQy38L/OpzSkoUSSQV1gHVpQvE8BVYE1gMT2jThNF10HrsGwehIpbfD2TQzzQgUUD1iEiCXpRs7EzMuDMWb+/WjPhh6GCFH97X2Cr3fibn8kmHQviSpPaySmnJHNhA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
